---
- name: Set ufw rules
  hosts: localhost
  become: true

  tasks:
    - name: Set firewall rule
      shell: "ufw {{ rule }} {{ port }}"

    - name: Check firewall rules
      shell: ufw status verbose