---
- name: Set ufw rules
  hosts: localhost
  become: true

  tasks:

    - name: Set firewall rule
      ufw: 
        rule: "{{ rule }}"
        name: "{{ name }}"

    - name: Check firewall rules
      shell: ufw status verbose