---
- name: Set ufw rules
  hosts: localhost
  become: true

- name: Set firewall rule
  community.general.ufw: 
     rule: "{{ rule }}"
     port: "{{ port }}"

- name: Check firewall rules
  shell: ufw status verbose